version: "2"
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-1-23-0
  duplication:
    enabled: true
    config:
      languages:
      - ruby
exclude_patterns:
- "**/*.yml"
- "**/*.js"
- "**/*.json"
- app/assets/**/*
- app/views/**/*
- bin/**/*
- config/**/*
- db/**/*
- lib/**/*
- log/**/*
- public/**/*
- spec/**/*
- tmp/**/*
- vendor/**/*
- .env*
- .gitattributes
- .gitignore
- .rspec
- .slugignore
- Gemfile
- Gemfile.lock
- Procfile
- README.md
- Rakefile
- config.ru
