dist: trusty
sudo: false
language: ruby
rvm:
  - 2.5.3
branches:
  only:
    - master
env:
  global:
    - DB_USER=postgres
    - DB_PASS=
services:
  - postgresql
before_script:
  - bundle exec rails db:create
  - bundle exec rails db:migrate
  - bundle exec rails db:test:prepare
script:
  - xvfb-run -a bundle exec rails spec
after_success:
  - bundle exec codeclimate-test-reporter
addons:
  apt:
    packages:
      - qt5-default
      - libqt5webkit5-dev
      - gstreamer1.0-plugins-base
      - gstreamer1.0-tools
      - gstreamer1.0-x
      - xvfb
  code_climate:
    repo_token: 88aeb5befc237aca41dd7b3d65025474be53470fa0eb358572d17c866d983672
deploy:
  provider: heroku
  app: bizusafo
  api_key:
    secure: Mhp7jMUuzRVdu4QMOBIEqh5Bol6ZqtmK2xaFSxUsERieNysWtanL3m0KYsTJ4YrlLnns1f/YLkgYwazw4q4hqzm7m0PVL6KOLCvs1h9/4JpLya030cJX4OF8X0uwZQu/kmV8C+w3D/VdnPzx1hZj/yPG78Rd0eyk3ZYgzoMKcxI=
  run:
    - "rails db:migrate"
