dist: xenial
sudo: false
language: ruby
rvm:
- 2.6.3
branches:
  only:
  - master
env:
  global:
  - DB_USER=postgres
  - DB_PASS=
services:
- postgresql
before_install:
- gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
- gem install bundler -v '< 2'
before_script:
- bundle exec rails db:create
- bundle exec rails db:migrate
- bundle exec rails db:test:prepare
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
script:
- bundle exec rails spec
after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
deploy:
  provider: heroku
  app: bizusafo
  api_key:
    secure: CKdBgkIcNa1w8BzrLxrpCietGAz0f5iBu0cOnhsCw7kSX+7Grxq+d0F3nvfzUaJwQi3AnXAw1s6EbuQS1Lc2rz3duNM9bjS9wKa5Q2F34C3w+Gtl9oLn8HbOO6L2zsQ4wB13pkFaqJocsQVZFmCpQVFwXDlOTh1GC//qeYbTMjo=
  run:
  - rails db:migrate
