version: '3.7'

services:
  postgres:
    image: postgres:10.6-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:4.0.10-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  postgres-data:

